export const listFilms = [
    {
        id: 1,
        Image: require('./bietdoidanhthue.jpg'),
        Title: 'The Expendables (Season 4)',
        Year: '2023',
        Nation: 'Âu - Mỹ',
        Description: `Biệt Đội Đánh Thuê (Phần 4) gồm cả các gương mặt kỳ cựu và những tân binh - đã bắt đầu một nhiệm vụ mới. Lần này, họ sẽ tới một nhà máy vũ khí hạt nhân cũ tại Qadhafi để tóm gọn Suharato Rahmat, kẻ đang âm mưu một mình đánh cắp kíp nổ hạt nhân cho gã khách hàng xảo quyệt Ocelot. Rahmat từng là một tay buôn vũ khí người Anh với đội quân của riêng mình. Hắn đã thành công đánh cắp va li chứa kíp nổ trước khi Biệt Đội Đánh Thuê kịp tìm đến. Nếu kíp nổ rơi vào tay Ocelot, gã sẽ hủy diệt cả thế giới. Sau khi nhiệm vụ tóm gọn Rahmat thất bại, cả đội tiếp tục hành trình trên con thuyền Jantara, nơi bước ngoặt thực sự của câu chuyện xảy ra, và một sự thật gây sốc về Ocelot được hé lộ…`,
    },
    {
        id: 2,
        Image: require('./darkharvest.jpg'),
        Title: 'DARK HARVEST',
        Year: '2023',
        Nation: 'Âu - Mỹ',
        Description: `Dark Harvest kể về tại một thị trấn bị nguyền rủa, vụ thu hoạch hàng năm trở thành một cuộc chiến sinh tồn tàn khốc. Vào Halloween năm 1963, Sawtooth Jack, một huyền thoại đáng sợ, trỗi dậy từ cánh đồng ngô, đe dọa trẻ em trong thị trấn. Các nhóm nam sinh đoàn kết để đánh bại tên bù nhìn sát nhân trước nửa đêm. Richie, một kẻ nổi loạn bị ruồng bỏ, tham gia cuộc chạy trốn, được thúc đẩy bởi chiến thắng trước đó của anh trai mình. Khi cuộc săn tiến triển, Richie có một phát hiện gây sốc và phải đối mặt với lựa chọn then chốt nhằm phá vỡ vòng luẩn quẩn không ngừng nghỉ.`,
    },
    {
        id: 3,
        Image: require('./dinhthumaam.jpg'),
        Title: 'Haunted Mansion',
        Year: '2023',
        Nation: 'Âu - Mỹ',
        Description: `Dinh Thự Ma Ám kể về một bà mẹ đơn thân tên Gabbie thuê một hướng dẫn viên du lịch, một nhà ngoại cảm, một linh mục và một nhà sử học để giúp trừ tà cho căn biệt thự mới mua của họ; sau khi phát hiện ra nó là nơi sinh sống của ma.`,
    },
    {
        id: 4,
        Image: require('./hoinghichetchoc.jpg'),
        Title: 'The Conference',
        Year: '2023',
        Nation: 'Âu - Mỹ',
        Description: `Hội Nghị Chết Chóc kể về trong kỳ nghỉ tưởng chừng vô hại, một nhóm nhân viên khu vực công đủ thành phần không chỉ chiến đấu với mối bất hòa của chính họ mà còn với tên sát nhân khát máu`,
    },
    {
        id: 5,
        Image: require('./majnu.jpg'),
        Title: 'Mission Majnu',
        Year: '2023',
        Nation: 'Ấn Độ',
        Description: `Nhiệm Vụ Majnu kể về những năm 1970, một điệp viên chìm của Ấn Độ đảm nhận một nhiệm vụ nguy hiểm: vạch trần chương trình vũ khí hạt nhân bí mật ở trung tâm Pakistan.`,
    },
    {
        id: 6,
        Image: require('./phonganquydu.jpg'),
        Title: 'It Lives Insid',
        Year: '2023',
        Nation: 'Âu - Mỹ',
        Description: `Phong Ấn Quỷ Dữ kể về một thiếu niên người Mỹ gốc Ấn đang vật lộn với bản sắc văn hóa của mình đã bất hòa với người bạn thân cũ của mình và trong quá trình đó đã vô tình giải phóng một thực thể ma quỷ ngày càng mạnh hơn bằng cách ăn sống sự cô đơn của cô.`,
    },
    {
        id: 7,
        Image: require('./thehill.jpg'),
        Title: 'The Hill',
        Year: '2023',
        Nation: 'Âu - Mỹ',
        Description: `The Hill kể về Rickey Hill, người đã vượt qua tình trạng khuyết tật về thể chất và hàn gắn mối quan hệ với cha mình trong nỗ lực trở thành cầu thủ bóng chày của giải đấu lớn (MLB).`,
    },
    {
        id: 8,
        Image: require('./thienacdoidau.jpg'),
        Title: 'The Equalizer (Season 3)',
        Year: '2023',
        Nation: 'Âu - Mỹ',
        Description: `Thiện Ác Đối Đầu (Phần 3) kể về Robert McCall chuyển đến sinh sống tại miền Nam nước Ý nhưng phát hiện ra bạn bè của mình bị một tổ chức mafia ở địa phương kiểm soát. Khi tính mạng của họ bị đe dọa, ông buộc phải quay trở lại con đường sát thủ để bảo vệ bạn bè.`,
    },
    {
        id: 9,
        Image: require('./thenun2.jpg'),
        Title: 'The Nun II',
        Year: '2023',
        Nation: 'Âu - Mỹ',
        Description: `Ác Quỷ Ma Sơ 2 là phần phim tiếp nối câu chuyện năm 2019 của The Nun, phim lấy bối cảnh nước Pháp năm 1956, cùng cái chết bí ẩn của một linh mục, một giai thoại đáng sợ và ám ảnh sẽ mở ra tiếp tục xoay quanh nhân vật chính - Sơ Irene. Liệu Sơ Irene có nhận ra, đây chính là hồn ma nữ tu Valak từng có cuộc chiến “sống còn” với cô không lâu trước đây.`,
    },
];
